#ifndef REPLY_CODES_HPP
#define REPLY_CODES_HPP


/// @brief https://datatracker.ietf.org/doc/html/rfc2812#section-5
enum ReplyCode {

	// post registration
	RPL_WELCOME = 001,
	
	// channel info
	RPL_NONE = 300,					// used to mark no answer
	RPL_NOTOPIC = 331,				// TOPIC
	RPL_TOPIC = 332,				// TOPIC
	RPL_INVITING = 341,				// INVITE
	RPL_YOUREOPER = 381,			// OPER
	RPL_TIME = 391,					// TIME

	// errors
	ERR_NOSUCHNICK = 401,
	ERR_NOSUCHCHANNEL = 403,
	ERR_CANNOTSENDTOCHAN = 404,		// PRIVMSG
	ERR_TOOMANYCHANNELS = 405,
	ERR_TOOMANYTARGETS = 407,		// PRIVMSG
	ERR_NOORIGIN = 409,				// PING, PONG
	ERR_NORECIPIENT = 411,
	ERR_NOTEXTTOSEND = 412,			// PRIVMSG
	ERR_NOTOPLEVEL = 413,			// PRIVMSG
	ERR_WILDTOPLEVEL = 414,			// PRIVMSG
	ERR_UNKNOWNCOMMAND = 421,
	ERR_FILEERROR = 424,			// BONUS
	ERR_NONICKNAMEGIVEN = 431,		// NICK
	ERR_ERRONEUSNICKNAME = 432,		// NICK
	ERR_NICKNAMEINUSE = 433,		// NICK
	ERR_USERNOTINCHANNEL = 441,		
	ERR_NOTONCHANNEL = 442,
	ERR_NOTREGISTERED = 451,		
	ERR_NEEDMOREPARAMS = 461,
	ERR_ALREADYREGISTERED = 462,	// PASS
	ERR_PASSWDMISMATCH = 464,		// PASS
	ERR_CHANNELISFULL = 471,
	ERR_UNKNOWNMODE = 472,			// MODE
	ERR_INVITEONLYCHAN = 473,
	ERR_CHANOPRIVSNEEDED = 482,
	ERR_UMODEUNKNOWNFLAG = 501,		// MODE
	
	// custom
	SERVER_ERR = 801,
	FORMAT_ERR = 802,
	PWD_ERR = 803

};

#endif